<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net8.0-android</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Stripe.UiCore</PackageId>
		<PackageVersion>21.6.0.2</PackageVersion>
		<AssemblyVersion>21.6.0.2</AssemblyVersion>
		<FileVersion>21.6.0.2</FileVersion>
		<Version>21.6.0.2</Version>
		<Title>Anjo Android Stripe UiCore SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Stripe</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Stripe UiCore SDK</Description>
		<PackageReleaseNotes>Stripe.UiCore SDK v21.6.0</PackageReleaseNotes>
		<Copyright>Copyright (c) 2025 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, MonoDroid, Stripe, credit cards, Payment Gateway, money</PackageTags>
		<Summary>With Stripe Payments, collect payments, make payouts, manage international payments and more.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\stripe-ui-core-21.6.0.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Xamarin.AndroidX.Activity" Version="1.10.1" />
		<PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.9.1.2" />
		<PackageReference Include="Xamarin.AndroidX.Compose.Foundation" Version="1.7.8" />
		<PackageReference Include="Xamarin.AndroidX.Compose.Material" Version="1.7.8" />
		<PackageReference Include="Xamarin.AndroidX.Compose.Material.Icons.Core" Version="1.7.8" />
		<PackageReference Include="Xamarin.AndroidX.Compose.Material.Ripple" Version="1.7.8" />
		<PackageReference Include="Xamarin.AndroidX.Compose.UI" Version="1.7.8" />
		<PackageReference Include="Xamarin.AndroidX.Compose.UI.Tooling.Preview" Version="1.7.8" />
		<PackageReference Include="Xamarin.AndroidX.Core" Version="1.15.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Common.Jvm" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Android" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.8.7.2" />
		<PackageReference Include="Xamarin.Google.Dagger" Version="2.55.0.1" />
		<PackageReference Include="Xamarin.Kotlin.StdLib" Version="2.0.21.2" />
		<PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="2.0.21.2" />
		<PackageReference Include="Xamarin.KotlinX.Coroutines.Android" Version="1.9.0.2" />
		<PackageReference Include="Xamarin.KotlinX.Coroutines.Core" Version="1.9.0.2" />
		<PackageReference Include="Xamarin.KotlinX.Serialization.Core.Jvm" Version="1.7.3.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\StripeCore\StripeCore.csproj" />
	</ItemGroup>
</Project>