<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0-android;net6.0-android;</TargetFrameworks>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Stripe.3DSecue</PackageId>
		<PackageVersion>6.1.7</PackageVersion>
		<AssemblyVersion>6.1.7</AssemblyVersion>
		<FileVersion>6.1.7</FileVersion>
		<Version>6.1.7</Version>
		<Title>Anjo Android Stripe 3DS2 SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Stripe</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Description>Xamarin Android Binding Library - Stripe 3DS2</Description>
		<PackageReleaseNotes>Stripe.3DS2 SDK v6.1.7</PackageReleaseNotes>
		<Copyright>Copyright (c) 2023 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, MonoDroid, Stripe, credit cards, Payment Gateway, money</PackageTags>
		<Summary>With Stripe Payments, collect payments, make payouts, manage international payments and more.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Xamarin.Android.JetBrains.Kotlin_Parcelize_Runtime" Version="1.5.20.1" />
		<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.6.1" />
		<PackageReference Include="Xamarin.AndroidX.Core" Version="1.9.0.2" />
		<PackageReference Include="Xamarin.AndroidX.DataBinding.ViewBinding" Version="7.4.2" />
		<PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.5.6" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.6.1" />
		<PackageReference Include="Xamarin.Google.Android.Material" Version="1.8.0" />
		<PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="1.8.10" />
		<PackageReference Include="Xamarin.KotlinX.Coroutines.Core" Version="1.6.4.2" />
		<PackageReference Include="Xamarin.KotlinX.Coroutines.Android" Version="1.6.4.2" />
	</ItemGroup>
</Project>